name: Automacao ETL SIAB_PATIO

on:
  # Gatilho para ser acionado manualmente ou via macro do Excel
  workflow_dispatch: 
  
  # Agendamento Automático
  schedule:
    - cron: '00 10,16,17,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Puxar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' 

      - name: Instalar bibliotecas
        # Como você já tem o arquivo requirements.txt, usamos ele para instalar tudo de uma vez
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar arquivo de credenciais do Google
        # Injeta o texto do seu JSON secreto e cria o arquivo fisicamente no servidor
        env:
          CONTEUDO_JSON: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$CONTEUDO_JSON" > credenciais_google.json

      - name: Executar o Script ETL
        env:
          CPF_USUARIO: ${{ secrets.CPF_USUARIO }}
          SENHA_BS: ${{ secrets.SENHA_BS }}
          # A GRANDE SACADA: Informamos ao Python que o "GCP_CREDENTIALS" é o nome do arquivo recém-criado
          GCP_CREDENTIALS: credenciais_google.json
        run: |
          python gestao_patio.py
