name: Automacao ETL SIAB_PATIO
on:
  schedule:
    # Seus horários automáticos continuam rodando normalmente
    - cron: '30 10,16,17,19 * * *'
  
  # ESSE É O COMANDO QUE CRIA O BOTÃO MANUAL
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Puxar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Acelera a instalação nas próximas vezes

      - name: Instalar bibliotecas
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar arquivo de credenciais do Google
        # Injeta o texto do seu JSON secreto e cria o arquivo fisicamente no servidor
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > credenciais_google.json

      - name: Executar o Script ETL
        # Injeta as senhas no ambiente para o os.getenv do Python conseguir ler
        env:
          CPF_USUARIO: ${{ secrets.CPF_USUARIO }}
          SENHA_BS: ${{ secrets.SENHA_BS }}
        run: |
          python gestao_patio.py
